In [8]:
import pandas as pd
import numpy as np

In [9]:
data = pd.read_csv("C:\\Users\\DELL\\Downloads\\Bengaluru_House_Data.csv")

In [10]:
data.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [11]:
data.shape

(13320, 9)

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   area_type     13320 non-null  object
 1   availability  13320 non-null  object
 2   location      13319 non-null  object
 3   size          13304 non-null  object
 4   society       7818 non-null   object
 5   total_sqft    13320 non-null  object
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB

In [13]:
for column in data.columns:
    print(data[column].value_counts())
    print("*"*20)

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64
********************
availability
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: count, Length: 81, dtype: int64
********************
location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64
********************
size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64
********************
society
GrrvaGr    80
PrarePa    76
Sryalan    59
Prtates    59
GMown E    56
           ..
Amionce     1
JaghtDe     1
Jauraht     1
Brity U     1
RSntsAp     1
Name: count, Length: 2688, dtype: int64
********************
total_sqft
1200    843
1100    221
1500    205
2400    196
600     180
       ...
3580      1
2461      1
1437      1
2155      1
4689      1
Name: count, Length: 2117, dtype: int64
********************
bath
2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: count, dtype: int64
********************
balcony
2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: count, dtype: int64
********************
price
75.00     310
65.00     302
55.00     275
60.00     270
45.00     240
         ...
351.00      1
54.10       1
80.64       1
32.73       1
488.00      1
Name: count, Length: 1994, dtype: int64
********************

In [14]:
data.isna().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [15]:
data.drop(columns=['area_type','availability','society','balcony'],inplace=True)

In [16]:
data.describe()

               bath         price
count  13247.000000  13320.000000
mean       2.692610    112.565627
std        1.341458    148.971674
min        1.000000      8.000000
25%        2.000000     50.000000
50%        2.000000     72.000000
75%        3.000000    120.000000
max       40.000000   3600.000000

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13319 non-null  object
 1   size        13304 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13247 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [18]:
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: count, Length: 1305, dtype: int64

In [19]:
data['location']=data['location'].fillna('Sarjarpur Road')

In [20]:
data['size'].value_counts()

size
2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: count, dtype: int64

In [21]:
data['size']=data['size'].fillna('2 BHK')

In [22]:
data['bath']=data['bath'].fillna(data['bath'].median())

In [23]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   location    13320 non-null  object
 1   size        13320 non-null  object
 2   total_sqft  13320 non-null  object
 3   bath        13320 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB

In [24]:
data['bhk'] = data['size'].str.split().str.get(0).astype(int)

In [25]:
data[data.bhk>20]

                       location        size total_sqft  bath  price  bhk
1718  2Electronic City Phase II      27 BHK       8000  27.0  230.0   27
4684                Munnekollal  43 Bedroom       2400  40.0  660.0   43

In [26]:
data['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [29]:
def convertRange(x):
    
    temp = x.split('-')
    if len(temp)==2:
        return(float(temp[0])+ float(temp[1]))/2
    try:
        return float(x)
    except:
        return None

In [30]:
data['total_sqft']=data['total_sqft'].apply(convertRange)

In [31]:
data.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [32]:
#Price per square foot

In [34]:
data['price_per_sqft']=data['price']*100000/data['total_sqft']

In [35]:
data['price_per_sqft']

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [36]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [39]:
data['location'].value_counts()

location
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ...
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Uvce Layout                         1
Abshot Layout                       1
Name: count, Length: 1306, dtype: int64

In [40]:
data['location']=data['location'].apply(lambda x: x.strip())
location_count=data['location'].value_counts()

In [42]:
location_count_less_10=location_count[location_count<=10]
location_count_less_10

location
BTM 1st Stage                         10
Nagadevanahalli                       10
Basapura                              10
Sector 1 HSR Layout                   10
Dairy Circle                          10
                                      ..
1Channasandra                          1
Hosahalli                              1
Vijayabank bank layout                 1
near Ramanashree California resort     1
Abshot Layout                          1
Name: count, Length: 1054, dtype: int64

In [43]:
data['location'] = data['location'].apply(
    lambda x: 'other' if x in location_count_less_10 else x
)

In [46]:
data['location'].value_counts()

location
other                 2886
Whitefield             541
Sarjapur  Road         399
Electronic City        304
Kanakpura Road         273
                      ...
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: count, Length: 242, dtype: int64

In [47]:
#Outliers detection and removal

In [48]:
data.describe()

         total_sqft          bath         price           bhk  price_per_sqft
count  13274.000000  13320.000000  13320.000000  13320.000000    1.327400e+04
mean    1559.626694      2.688814    112.565627      2.802778    7.907501e+03
std     1238.405258      1.338754    148.971674      1.294496    1.064296e+05
min        1.000000      1.000000      8.000000      1.000000    2.678298e+02
25%     1100.000000      2.000000     50.000000      2.000000    4.266865e+03
50%     1276.000000      2.000000     72.000000      3.000000    5.434306e+03
75%     1680.000000      3.000000    120.000000      3.000000    7.311746e+03
max    52272.000000     40.000000   3600.000000     43.000000    1.200000e+07

In [57]:
(data['total_sqft']/data['bhk']).describe()

count    10976.000000
mean       590.572270
std        284.343625
min        300.000000
25%        493.500000
50%        562.500000
75%        627.500000
max      17424.000000
dtype: float64

In [52]:
data=data[((data['total_sqft']/data['bhk'])>=300)]

In [58]:
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,10976.000000,10976.000000,10605.000000,10976.000000,10976.000000,10976.000000
mean,1557.004336,2.523779,1.590193,104.369048,2.614249,6055.956385
std,1157.745690,1.041105,0.801556,140.594952,0.938507,3312.364608
min,300.000000,1.000000,0.000000,10.000000,1.000000,267.829813
25%,1115.000000,2.000000,1.000000,49.500000,2.000000,4256.686930
50%,1299.000000,2.000000,2.000000,68.690000,2.000000,5241.935484
75%,1680.000000,3.000000,2.000000,109.000000,3.000000,6666.666667
max,52272.000000,16.000000,3.000000,3600.000000,16.000000,53150.000000

In [59]:
data.shape

(10976, 11)

In [60]:
data.price_per_sqft.describe()

count    10976.000000
mean      6055.956385
std       3312.364608
min        267.829813
25%       4256.686930
50%       5241.935484
75%       6666.666667
max      53150.000000
Name: price_per_sqft, dtype: float64

In [61]:
def remove_pps_outliers(df):
    df_out = pd.DataFrame()
    for key, subdf in df.groupby('location'):
        m = np.mean(subdf.price_per_sqft)
        st = np.std(subdf.price_per_sqft)
        df_clean = subdf[(subdf.price_per_sqft > (m - st)) & (subdf.price_per_sqft < (m + st))]
        df_out = pd.concat([df_out, df_clean], ignore_index=True)
    return df_out

data = remove_pps_outliers(data)
data.describe()

,total_sqft,bath,balcony,price,bhk,price_per_sqft
count,8033.000000,8033.000000,7795.000000,8033.000000,8033.000000,8033.000000
mean,1495.916219,2.461720,1.597306,88.499940,2.564422,5580.557054
std,897.287798,0.971101,0.794915,78.915007,0.891591,2073.086932
min,300.000000,1.000000,0.000000,10.000000,1.000000,2222.222222
25%,1110.000000,2.000000,1.000000,50.000000,2.000000,4285.714286
50%,1280.000000,2.000000,2.000000,66.880000,2.000000,5148.514851
75%,1631.000000,3.000000,2.000000,96.900000,3.000000,6257.309942
max,30400.000000,16.000000,3.000000,2100.000000,16.000000,24509.803922

In [62]:
def bhk_outlier_remover(df):
    exclude_indices = np.array([])
    
    for location, location_df in df.groupby('location'):
        bhk_stats = {}
        
        for bhk, bhk_df in location_df.groupby('bhk'):
            bhk_stats[bhk] = {
                'mean': np.mean(bhk_df.price_per_sqft),
                'std': np.std(bhk_df.price_per_sqft),
                'count': bhk_df.shape[0]
            }
        
        # Now detect outliers and mark indices to remove
        for bhk, bhk_df in location_df.groupby('bhk'):
            stats = bhk_stats.get(bhk - 1)
            if stats and stats['count'] > 5:
                exclude_indices = np.append(
                    exclude_indices,
                    bhk_df[bhk_df.price_per_sqft < (stats['mean'])].index.values
                )
                
    
    return df.drop(exclude_indices, axis='index')

In [63]:
data=bhk_outlier_remover(data)

In [64]:
data.shape

(5570, 11)

In [65]:
data

,area_type,availability,location,size,society,total_sqft,bath,balcony,price,bhk,price_per_sqft
0,Super built-up Area,18-Jun,1st Block Jayanagar,3 BHK,NaN,1630.0,3.0,2.0,194.0,3,11901.840491
1,Super built-up Area,Ready To Move,1st Block Jayanagar,3 BHK,NaN,1875.0,2.0,3.0,235.0,3,12533.333333
2,Super built-up Area,18-Jun,1st Block Jayanagar,2 BHK,NaN,1235.0,2.0,2.0,148.0,2,11983.805668
3,Super built-up Area,Ready To Move,1st Phase JP Nagar,4 BHK,Prhtsok,2825.0,4.0,3.0,250.0,4,8849.557522
4,Super built-up Area,Ready To Move,1st Phase JP Nagar,3 BHK,Prhtsok,1875.0,3.0,1.0,167.0,3,8906.666667
...,...,...,...,...,...,...,...,...,...,...,...
8024,Carpet Area,19-Jan,other,2 BHK,NaN,1200.0,2.0,3.0,70.0,2,5833.333333
8025,Super built-up Area,Ready To Move,other,1 BHK,NaN,1800.0,1.0,1.0,200.0,1,11111.111111
8028,Super built-up Area,Ready To Move,other,2 BHK,OlarkLa,1353.0,2.0,2.0,110.0,2,8130.081301
8029,Plot Area,18-Jan,other,1 Bedroom,NaN,812.0,1.0,0.0,26.0,1,3201.970443
8032,Super built-up Area,Ready To Move,other,4 BHK,NaN,3600.0,5.0,NaN,400.0,4,11111.111111

In [66]:
data.drop(columns=['size','price_per_sqft'],inplace=True)

In [67]:
data

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1630.0,3.0,2.0,194.0,3
1,Super built-up Area,Ready To Move,1st Block Jayanagar,NaN,1875.0,2.0,3.0,235.0,3
2,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1235.0,2.0,2.0,148.0,2
3,Super built-up Area,Ready To Move,1st Phase JP Nagar,Prhtsok,2825.0,4.0,3.0,250.0,4
4,Super built-up Area,Ready To Move,1st Phase JP Nagar,Prhtsok,1875.0,3.0,1.0,167.0,3
...,...,...,...,...,...,...,...,...,...
8024,Carpet Area,19-Jan,other,NaN,1200.0,2.0,3.0,70.0,2
8025,Super built-up Area,Ready To Move,other,NaN,1800.0,1.0,1.0,200.0,1
8028,Super built-up Area,Ready To Move,other,OlarkLa,1353.0,2.0,2.0,110.0,2
8029,Plot Area,18-Jan,other,NaN,812.0,1.0,0.0,26.0,1
8032,Super built-up Area,Ready To Move,other,NaN,3600.0,5.0,NaN,400.0,4

In [68]:
#Cleaned Data

In [69]:
data.head()

,area_type,availability,location,society,total_sqft,bath,balcony,price,bhk
0,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1630.0,3.0,2.0,194.0,3
1,Super built-up Area,Ready To Move,1st Block Jayanagar,NaN,1875.0,2.0,3.0,235.0,3
2,Super built-up Area,18-Jun,1st Block Jayanagar,NaN,1235.0,2.0,2.0,148.0,2
3,Super built-up Area,Ready To Move,1st Phase JP Nagar,Prhtsok,2825.0,4.0,3.0,250.0,4
4,Super built-up Area,Ready To Move,1st Phase JP Nagar,Prhtsok,1875.0,3.0,1.0,167.0,3

In [70]:
data.to_csv("Cleaned_data.csv")

In [83]:
X=data.drop(columns=['price'])
y=data['price']

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer

# ------------------------------
# Train-test split
# ------------------------------
X = data.drop('price', axis=1)
y = data['price']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=0
)

# ------------------------------
# Detect columns
# ------------------------------
categorical_cols = X.select_dtypes(include='object').columns.tolist()
numeric_cols = X.select_dtypes(exclude='object').columns.tolist()

# ------------------------------
# Preprocessing
# ------------------------------
column_trans = make_column_transformer(
    # 1. Categorical: impute missing → one-hot encode
    (
        make_pipeline(
            SimpleImputer(strategy='most_frequent'),
            OneHotEncoder(handle_unknown='ignore', sparse=False)
        ),
        categorical_cols
    ),
    # 2. Numeric: impute missing → scale
    (
        make_pipeline(
            SimpleImputer(strategy='median'),
            StandardScaler()
        ),
        numeric_cols
    )
)

# ------------------------------
# Model
# ------------------------------
lr = LinearRegression()

pipe = make_pipeline(column_trans, lr)

# ------------------------------
# Fit
# ------------------------------
pipe.fit(X_train, y_train)

# ------------------------------
# Predict
# ------------------------------
y_pred_lr = pipe.predict(X_test)

# ------------------------------
# Score
# ------------------------------
print("R2 Score:", r2_score(y_test, y_pred_lr))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

R2 Score: -4.409232017430977e+17

In [95]:
#Apllying Lasso

In [97]:
from sklearn.linear_model import Lasso

lasso = Lasso()

pipe_lasso = make_pipeline(column_trans, scaler, lasso)

pipe_lasso.fit(X_train, y_train)

y_pred_lasso = pipe_lasso.predict(X_test)

print("Lasso R2 Score:", r2_score(y_test, y_pred_lasso))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Lasso R2 Score: 0.8658917963155456

In [98]:
#Aplling zRidge

In [99]:
from sklearn.linear_model import Ridge

ridge = Ridge()

pipe= make_pipeline(column_trans, scaler, ridge)

pipe.fit(X_train, y_train)

y_pred_ridge = pipe.predict(X_test)

print("Ridge R2 Score:", r2_score(y_test, y_pred_ridge))

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

Ridge R2 Score: 0.8870134881847447

In [101]:
import pickle

In [102]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))